### PR TITLE
Adds Protobuf SerDes

### PR DESCRIPTION
**Pull request by mmhealey1**
- Adds SchemaProtoSerDes and unit tests with order and person examples mimicking the unit tests for avro

- Adds an abstract SchemaRegistry.SerDes that avro SchemaRegistry.SerDes.Avro inherits from

- Changes comment in StreamException to be generic SchemaSerDes instead of SchemaAvroSerDes

#64

### CODE REVIEW

**Comment by mmhealey1** [comment]
@LGouellec give me your thoughts when you have some time :)

**Comment by fglaeser** [comment]
Hi @mmhealey1  don't you think that it is better to use the word Protobuf instead Proto, in namespaces and Classes name?

**Comment by mmhealey1** [comment]
I agree, I can make that change on Monday.

**Comment by LGouellec** [comment]
Hi @mmhealey1, 

First, many thanks for your PR.
Just a little point, Can you move these folders into serdes root folder please ? 
- Streamiz.Kafka.Net.SchemaRegistry.SerDes
- Streamiz.Kafka.Net.SchemaRegistry.SerDes.Proto (rename to Streamiz.Kafka.Net.SchemaRegistry.SerDes.Protobuf)

Thanks 👍

**Comment by LGouellec** [comment]
Last point, maybe we should merge these two project Streamiz.Kafka.Net.SchemaRegistry.SerDes & Streamiz.Kafka.Net.SchemaRegistry.Mock into one, maybe in Streamiz.Kafka.Net.SchemaRegistry.SerDes project.
No sense, to have two projects and generate too much dependencies. 
Do you agree with me ? 

If yes, move Streamiz.Kafka.Net.SchemaRegistry.Mock classes to Streamiz.Kafka.Net.SchemaRegistry.SerDes, remove crosscutting folder, and your PR is ok for me :)

**Comment by mmhealey1** [comment]
@LGouellec what do you want to do about namespaces for the classes currently in Streamiz.Kafka.Net.SchemaRegistry.Mock? Do you want to change the namespace to Streamiz.Kafka.Net.SchemaRegistry.SerDes or to Streamiz.Kafka.Net.SchemaRegistry.SerDes.Mock or leave it as Streamiz.Kafka.Net.SchemaRegistry.Mock?

**Comment by LGouellec** [comment]
Thanks for you job ! Welcome in contributor list on Streamiz project :)

**Pull request merged**
