### PR TITLE
Updated to net5

### PR DESCRIPTION
**Pull request by TheRubble**

### CODE REVIEW

**Comment by TheRubble** [comment]
As per https://github.com/LGouellec/kafka-streams-dotnet/issues/40, multitargeted the library itself as I didn't see a reason to lose netcore 3.1 support.

**Comment by LGouellec** [comment]
HI @TheRubble , 

First many thanks for your PR.
Great ! All unit tests passed. 👍 

Just a little point : 

These packages should always support .netstandard 2.1 :
- Streamiz.Kafka.Net.SchemaRegistry.Mock
- Streamiz.Kafka.Net.SchemaRegistry.SerDes.Avro

Thanks

**Comment by TheRubble** [comment]
Hi @LGouellec ,

I've updated the other projects, applied the changes to the new protobuf project and also amended the tests to run both netcoreapp3.1 and net5.0

Thanks

**Comment by LGouellec** [comment]
Thanks for you job ! Welcome in contributor list on Streamiz project :)

**Pull request merged**
