### PR TITLE
feat(Record): add Record.WithHeaders

### PR DESCRIPTION
**Pull request by attributeerror**
Add the ability to duplicate a record with a new set of headers. Confluent library only allows headers to be added to (not removed from, since the list is `readonly`), therefore this will allow the addition of headers between topics.

### CODE REVIEW

**Comment by LGouellec** [comment]
Hi @attributeerror, 

Can you add some unit tests to cover this new feature ? I'm not sure just adding `WithHeaders` will persist the new headers in the downstream record. 

Best regards,

**Comment by attributeerror** [comment]
Hey! I appreciate the quick review. Sure can- I intend for it to be used with a Transformer, so hopefully no issue with persisting the changes downstream as it shouldn't be any different from changing the key or value via a transformer.

**Comment by LGouellec** [comment]
Because I propagate only the new key/value in the downstream processors.

https://github.com/LGouellec/kafka-streams-dotnet/blob/4cd16fe7e25a5c7863fd957b8888c8e6684d4e42/core/Processors/KStreamTransformer.cs#L32

Headers is just passed from the `Context.RecordContext` in the Transform API for information (as a read-only). If you want to switch to a read-write model, you have to change the current headers in the RecordContext object after the transformer.

**Comment by attributeerror** [comment]
I suppose the next viable option would be to move this to RecordContext.WithHeaders to update the whole context rather than just one record? Let me know your thoughts- this is possible in the Java library so I'm confident there's a solution here 😅

**Comment by attributeerror** [comment]
Now that I'm back on a computer, I've just been looking into this. Would I be able to use a custom transformer class, which extends KStreamPAPI and forwards the new record on? This should ideally chain to the built-in transformer with the record being updated by calling `Forward` at the end of my custom one...

**Comment by attributeerror** [comment]
Hopefully those changes cover everything.. I've made 4 unit tests:
- No headers on input message, transform & add headers
- No headers on input message, don't transform & don't add headers
- 1 header on input message, transform & add header resulting in 2 headers.
- No headers on input message, transform & add headers and ensure a processor in between the two don't remove the headers.

**Comment by attributeerror** [comment]
Hey, @DatStorm !

I assume this will be released fairly soon- there's a milestone open for 1.5 so whenever all of the work on that front is complete.

I assume this will work for TransformValues providing you use a Transformer class like I did in the tests, but I didn't really look at this if I'm honest.

**Pull request merged**
