### PR TITLE
Offer manual control over Grace MS settings

### PR DESCRIPTION
**Pull request by yasinparsi**
Fixes https://github.com/LGouellec/kafka-streams-dotnet/issues/281

### CODE REVIEW

**Comment by yasinparsi** [comment]
If you want we can implement this for other classes like `TumblingWindowOptions` & `HoppingWindowOptions`

**Comment by LGouellec** [comment]
@yasinparsi 
Can you implement the same behavior for `TumblingWindowOptions` and `HoppingWindowOptions` ? I think it could be interesting and useful. 

Appreciate

**Comment by yasinparsi** [comment]
@LGouellec 
Ofcurse, I'll take care about it

**Comment by yasinparsi** [comment]
@LGouellec 
I've implemented

**Pull request merged**
