### PR TITLE
Hotfix/103

### PR DESCRIPTION
**Pull request by LGouellec**
See #103 and discussion #102

### CODE REVIEW

**Comment by RPalejiya** [comment]
Hi there, 

In my case this hotfix is not solving the issue of stream getting hangged as soon as I add aggregate. I can still reproduce the issue.

```

StreamBuilder streamBuilder = new StreamBuilder();
var s = streamBuilder.Stream<string, GenericRecord>("TOPIC");
var s = stream.Peek((k, v) => { Console.WriteLine(k); });
var grouped = stream.GroupBy(
                            //New Key Slection Function
                            (k, v) =>
                            {
                                StringBuilder s = new();
                                bool first = true;
                                foreach (var c in AggregateColumns)
                                {
                                    if (!first) s.Append("|");
                                    v.TryGetValue(c, out var f);
                                    s.Append(f);
                                    first = false;
                                }
                                Console.WriteLine("Grouped key:{0}", s.ToString());
                                return s.ToString();
                            }
                        );

//ADDING THIS HANGS THE STREAM
IKTable<string, double> kpiTable = grouped.Aggregate<double, DoubleSerDes>(
                                                    () => (double)0,  //Initializer
                                                    (k, v, sumvalue) //Aggregator
                                                        =>
                                                    {
                                                        v.TryGetValue("TSL", out var f);
                                                        var total = sumvalue + ((f is Avro.AvroDecimal) ? Avro.AvroDecimal.ToDouble((Avro.AvroDecimal)f) : (double)f);
                                                        Console.WriteLine(total);
                                                        return total;
                                                    });

var topology  = streamBuilder.Build();
var kafkaStream  = new KafkaStream(topology, StreamConfig);
kafkaStream.StartAsync().Wait();

```

**Comment by LGouellec** [comment]
Could you enable debug logging level and post this logs on this please ?

**Comment by RPalejiya** [comment]
Thanks for hint to make debug logging! Below was the error, surprising it was not reported without debug logging. 

It is resolved after removing colon from stream name. Thank you once again. 

```
[11:42:04 DBG] Error when creating all internal topics: An error occurred creating topics: [Aura-202226:16421-KSTREAM-AGGREGATE-STATE-STORE-0000000004-changelog, Aura-202226:16421-KSTREAM-AGGREGATE-STATE-STORE-0000000004-repartition]: [Topic name "Aura-202226:16421-KSTREAM-AGGREGATE-STATE-STORE-0000000004-changelog" is illegal, it contains a character other than ASCII alphanumerics, '.', '_' and '-', Topic name "Aura-202226**:**16421-KSTREAM-AGGREGATE-STATE-STORE-0000000004-repartition" is illegal, it contains a character other than ASCII alphanumerics, '.', '_' and '-'].. Maybe an another instance of your application just created them. (try: 2, max retry : 10)
[11:42:04 DBG] Starting to apply internal topics in topic manager (try: 2, max retry : 10).
[11:42:04 DBG] Error when creating all internal topics: An error occurred creating topics: [Aura-202226:16421-KSTREAM-AGGREGATE-STATE-STORE-0000000004-changelog, Aura-202226:16421-KSTREAM-AGGREGATE-STATE-STORE-0000000004-repartition]: [Topic name "Aura-202226:16421-KSTREAM-AGGREGATE-STATE-STORE-0000000004-changelog" is illegal, it contains a character other than ASCII alphanumerics, '.', '_' and '-', Topic name "Aura-202226:16421-KSTREAM-AGGREGATE-STATE-STORE-0000000004-repartition" is illegal, it contains a character other than ASCII alphanumerics, '.', '_' and '-'].. Maybe an another instance of your application just created them. (try: 3, max retry : 10)
[11:42:04 DBG] Starting to apply internal topics in topic manager (try: 3, max retry : 10).....
```

-Ravi

**Comment by LGouellec** [comment]
> Thanks for hint to make debug logging! Below was the error, surprising it was not reported without debug logging.
> 
> It is resolved after removing colon from stream name. Thank you once again.

Correct, I will change to warning or error level in future release

**Pull request merged**
